### ISSUE TITLE
Does not spin up in azure

### ISSUE THREAD

**Issue by generik0** [ThorstenHans/six-steps-to-aks#3]
Hi

I really liked your application.

However, I can simply not get it to spin up in Azure.
the acr is created, the kubernitis is created. but it just doesn't spin up. and connect the api..
It is like Kubernetes is not running a container instance.

Any thoughts?
Do I have to do something to make the Kubernetes startup a container instance?

![image](https://user-images.githubusercontent.com/2411563/101899518-3f765500-3bae-11eb-8263-c9a21bc90393.png)

**Comment by generik0** [comment]
PS. I get this issue in Azure when following instructions:
![image](https://user-images.githubusercontent.com/2411563/101903256-4acc7f00-3bb4-11eb-8b38-448e70b8881c.png)

**Comment by generik0** [comment]
My mistake. I did not change the name in the for mypod to the correct image.
AND updated the acr to attach  --attach-ac
az acr create -n $ACR_NAME -g hello-aks --admin-enabled false --sku Basic --attach-acr $MYACR

**Comment by ThorstenHans** [comment]
Thanks for reaching out. When facing similar issues, a good starting point is looking at Pod details using

```
kubectl describe pod my-pod
```

Second, is checking checking if the service is linked to a pod.

```
kubectl get ep

# or in combination with the service
kubectl get svc,ep
```

However, when the pod is in state `Running`, you could also query for the logs of your Docker container running in the pod using

```
kubectl logs my-pod
```

Hope that helps 🙌🏻

**Comment by generik0** [comment]
Hi.

Yes i got the Pod to work to work.
Thanks for your great example!!!

Br Rik
